version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - 81:81
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    privileged: true

  mysql:
    restart: always
    image: mysql:8.2.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=ASD.123456 # mysql root 密码
      - MYSQL_DATABASE=big_event
      - MYSQL_USER=wuyq54517
      - MYSQL_PASSWORD=ASD.123456
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/var/lib/mysql
      
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./redis/redis.conf:/etc/redis/redis.conf
    command: ["redis-server", "/etc/redis/redis.conf"]

  vuelibiary:
    image: vueblog:latest
    build: .
    ports:
      - 8080:8080
    depends_on:
      - mysql
      - redis

