version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - 81:81
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    privileged: true
  mysql:
    image: mysql:8.2.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=ASD.123456
  redis:
    image: redis:latest
  vueblog:
    image: vueblog:latest
    build: .
    ports:
      - 8080:8080
    depends_on:
      - mysql
      - redis
